import { Themes } from '../../contexts/ThemeContext/types';

export const colors: Themes = {
  light: {
    background: '#FFFFFF',
    subStepSection: '#EEEEEE',
    title: '#111111',
    text: '#111111',
    completedText: '#555555',
    nonCompletedSquare: '#111111',
    completedSquare: '#FF5A60',
    completedSquareCheck: '#FFFFFF',
    stepNonCompletedCircleOuter: '#333333',
    stepNonCompletedCircleInner: '#EEEEEE',
    stepCompletedCheck: '#FF5A60',
    floatButton: '#FF5A60',
    floatButtonIcon: '#FFFFFF',
    input: '#EEEEEE',
  },
  dark: {
    background: '#111111',
    subStepSection: '#222222',
    title: '#FFFFFF',
    text: '#FFFFFF',
    completedText: '#555555',
    nonCompletedSquare: '#555555',
    completedSquare: '#FF5A60',
    completedSquareCheck: '#111111',
    stepNonCompletedCircleOuter: '#555555',
    stepNonCompletedCircleInner: '#555555',
    stepCompletedCheck: '#FF5A60',
    floatButton: '#FF5A60',
    floatButtonIcon: '#111111',
    input: '#222222',
  },
  blue: {
    background: '#F2F6FF',
    subStepSection: '#E8EEFF',
    title: '#5C9DFE',
    text: '#111111',
    completedText: '#555555',
    nonCompletedSquare: '#BED8FF',
    completedSquare: '#5C9DFE',
    completedSquareCheck: '#F2F6FF',
    stepNonCompletedCircleOuter: '#BED8FF',
    stepNonCompletedCircleInner: '#E8EEFF',
    stepCompletedCheck: '#5C9DFE',
    floatButton: '#5C9DFE',
    floatButtonIcon: '#F2F6FF',
    input: '#E8EEFF',
  },
  green: {
    background: '#EBEBE3',
    subStepSection: '#DBDDD7',
    title: '#4E5851',
    text: '#4E5851',
    completedText: '#9CA59D',
    nonCompletedSquare: '#9CA59D',
    completedSquare: '#4E5851',
    completedSquareCheck: '#EBEBE3',
    stepNonCompletedCircleOuter: '#9CA59D',
    stepNonCompletedCircleInner: '#DBDDD7',
    stepCompletedCheck: '#4E5851',
    floatButton: '#4E5851',
    floatButtonIcon: '#EBEBE3',
    input: '#DBDDD7',
  },
  gold: {
    background: '#000000',
    subStepSection: '#322B26',
    title: '#FAD7BD',
    text: '#FAD7BD',
    completedText: '#5A4D44',
    nonCompletedSquare: '#FAD7BD',
    completedSquare: '#322B26',
    completedSquareCheck: '#000000',
    stepNonCompletedCircleOuter: '#FAD7BD',
    stepNonCompletedCircleInner: '#322B26',
    stepCompletedCheck: '#5A4D44',
    floatButton: '#FAD7BD',
    floatButtonIcon: '#000000',
    input: '#322B26',
  },
};
